### ISSUE TITLE
功能请求：桌面版添加打开 AList 网站的按钮

### ISSUE THREAD

**Issue by yjl9903** [alist-org/desktop-release#10]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

1. 目前，AList 在状态栏的图标右键点击后，只有 打开/关闭 UI 和 退出 两个按钮。希望添加一个按钮 "Open in Browswer", 直接在浏览器打开 AList 的 web app;
2. 桌面版的 UI 添加一个按钮 "打开"，直接在浏览器打开 AList 的 web app。

### Suggested solution / 实现思路

相关的打开浏览器 Go package: https://pkg.go.dev/github.com/pkg/browser#section-readme

可能的 UI 设计：

1. 在 AList Desktop 的标题后添加一个运行图标的按钮?
2. 在底下 4 个按钮中添加一个打开按钮，并重新组织这 4 个按钮 UI 的逻辑

![image](https://user-images.githubusercontent.com/30072175/233768933-aba12ec7-6a9b-4272-b397-cbc82b60782b.png)

### Additional context / 附件

例如 Jellyfin 的状态栏右键菜单：

![image](https://user-images.githubusercontent.com/30072175/233768889-1cdc7069-fd8a-437d-80f0-fcec2d427272.png)

**Comment by Xhofe** [comment]
已在3.16.1中更多中添加了“在浏览器打开”
