### ISSUE TITLE
大佬，阿里盘好像出问题了

### ISSUE THREAD

**Issue by wwwsure** [alist-org/desktop-release#13]
![image](https://github.com/alist-org/desktop-release/assets/80196042/cebdf7f1-2cbe-4bf9-bd65-ece6fc07f5e1)

**Comment by wwwsure** [comment]
![image](https://github.com/alist-org/desktop-release/assets/80196042/482ea3a7-98e4-4c05-9346-46f0d77bc6c9)

**Comment by Xhofe** [comment]
https://github.com/alist-org/alist/issues/4354#issuecomment-1543741157

原来的服务器线路被攻击了，新换的这个服务器是香港bgp的，但是好像有的网络连不上。你可以在上面的链接中找到备用的服务来使用。替换在这里
![image](https://github.com/alist-org/desktop-release/assets/36558727/39130b41-5801-40fe-a86c-7b862a980554)

**Comment by wwwsure** [comment]
> 
大佬，网站404了，还有就是之前的那个网站我挂了梯可以拿到token了，但是替换了保存不了一直转圈

**Comment by Xhofe** [comment]
？哪个网站404了

**Comment by wwwsure** [comment]
> ？哪个网站404了

![image](https://github.com/alist-org/desktop-release/assets/80196042/2bbbb5dd-26b4-4419-9ee5-7631482c2bd2)

**Comment by Xhofe** [comment]
https://api.nn.ci/alist/ali_open/limit

_不要换成%20啊

**Comment by wwwsure** [comment]
> https://api.nn.ci/alist/ali_open/token
> 
> _不要换成%20啊

![image](https://github.com/alist-org/desktop-release/assets/80196042/28dbf926-c877-44a4-8d50-5659c10489fd)

**Comment by Xhofe** [comment]
直接打开本来就是这样的 通过api调用才会有正确的结果。

**Comment by wwwsure** [comment]
> 直接打开本来就是这样的 通过api调用才会有正确的结果。

好啦好啦
