### ISSUE TITLE
更新提示无法关闭和选择

### ISSUE THREAD

**Issue by TianRex** [alist-org/desktop-release#14]
如图所示，系统为Win10 LTSC，屏幕尺寸15.6英寸，系统内缩放默认125%
![image](https://github.com/alist-org/desktop-release/assets/52886240/914ee13a-7bb2-4687-94cd-55ed7875b814)

**Comment by Xhofe** [comment]
tauri没有适配超长的日志，下个版本会直接将日志替换为一个指向release的链接。

你目前可用直接在弹出这个升级提示框时直接按键盘上的回车键，它默认聚焦在确定上。

**Comment by Mrered** [comment]
macOS遇到同样问题。

目前只能通过增加分辨率才能点按到按钮，希望改进。

![bug](https://user-images.githubusercontent.com/34948506/241145646-d15c8752-42b8-4a8c-9f36-56bc42dd72bd.png)

**Comment by Xhofe** [comment]
这在新版本中应该已经被修复
