### ISSUE TITLE
已经运行alist时，再次双击桌面图标应打开原窗口

### ISSUE THREAD

**Issue by whx1024** [alist-org/desktop-release#16]
如题，按桌面版应用逻辑，再次双击快捷方式时，应打开原窗口，或者提示：alist已在运行中。而不是打开一个新alist，提示failed to start: listen tcp 0.0.0.0:5244，使小白摸不到头脑（其实会用alist的都不是小白）

**Comment by Xhofe** [comment]
已经在 https://github.com/alist-org/desktop-release/releases/tag/v3.20.0 中实现。
