### ISSUE TITLE
[BUG] 百度网盘挂载到本地后大文件打不开

### ISSUE THREAD

**Issue by wx7i** [alist-org/desktop-release#18]
### 使用的存储驱动

百度网盘。

### 问题描述

如题。我感觉是 user-agent 的问题，能直接拦截本地挂载的文件请求，自动加上 user-agent 吗
？
### 复现步骤

无。

#### AList日志

无。

#### 挂载日志

无。

**Comment by Xhofe** [comment]
打开web代理 以及webdav策略中的使用本机代理，即可自动添加user-agent。

**Comment by wx7i** [comment]
> 打开web代理 以及webdav策略中的使用本机代理，即可自动添加user-agent。

但是这样很卡，不能直连百度api的时候自动带上吗

**Comment by Xhofe** [comment]
> > 打开web代理 以及webdav策略中的使用本机代理，即可自动添加user-agent。
> 
> 但是这样很卡，不能直连百度api的时候自动带上吗

无法实现 本地使用增加的只是本机之间的通信应该可以忽略的。卡主要还是取决于与百度网盘之间的速度
