### ISSUE TITLE
[ASK] windows的普通版和nsis般什么区别？

### ISSUE THREAD

**Issue by opptimus** [alist-org/desktop-release#28]
x64-setup.nsis.zip安装包和不带nsis标志的安装包有何区别？

**Comment by xhofe** [comment]
无区别 x64-setup.nsis.zip 是用于更新的 但是tauri目前似乎对于每个系统只支持一个更新配置，所以 x64-setup.exe 可能无法更新。对于Windows，优先推荐使用 msi的安装包
