### ISSUE TITLE
Way to pay outside of China

### ISSUE THREAD

**Issue by luckycold** [alist-org/desktop-release#30]
I'm sorry for not filling out the form in Chinese, I simply don't know it.

The main issue I wanted to bring up is that the only way to pay for the desktop app is to use Alipay or WeChat Pay, both of which are impossible to use for an American like myself. I tried to get my way through with Google Translate, but the problem is that it requires either a Chinese ID or a Chinese Bank account to use either. If another method of payment can be used for people outside of China, I would gladly pay for this app.

**Comment by xhofe** [comment]
You can pay at https://ko-fi.com/xhofe and contact me on it.
