### ISSUE TITLE
> 需要在存储配置中webdav策略选择本地代理

### ISSUE THREAD

**Issue by KyrieWang0410** [alist-org/desktop-release#35]
> 需要在存储配置中webdav策略选择本地代理

改为本地代理后是可以复制了，这个复制速度跟什么有关系，需要怎么配置，我的是超级会员。

_Originally posted by @KyrieWang0410 in https://github.com/alist-org/desktop-release/issues/34#issuecomment-1782638786_

**Comment by xhofe** [comment]
和网速相关。无需配置
