### ISSUE TITLE
windows挂在本地盘，在资源管理器中或者网络中找不到磁盘

### ISSUE THREAD

**Issue by woaiCarlos** [alist-org/desktop-release#38]
### 问题描述

windows挂在本地盘，在资源管理器中或者网络中找不到磁盘，但是用管理员模式打开powershell  输入cd F：是可以进入的
检查过权限，是everyone都可以操作查看

操作系统版本
Windows 11 专业版22H2
22621.2715

#### 挂载日志
start mounting...
The service rclone has been started.

**Comment by xhofe** [comment]
请在面包多上与我联系。
