### ISSUE TITLE
可以优化一下每次启动都需要重新填写key吗

### ISSUE THREAD

**Issue by wwwsure** [alist-org/desktop-release#4]
大佬，可以优化一下每次启动都需要重新填写key吗，不然感觉有点难受呀

**Comment by Xhofe** [comment]
key是记录在磁盘里的啊 应该不需要每次启动需要重新填写的。你可以检查一下`C:\Users\{username}\AppData\Roaming\ci.nn.alist\key`这个文件。

下个版本在localstorage里再存一份吧 应该可以改善这种情况。

**Comment by wwwsure** [comment]
俺这个目录下没有key这个文件，哈哈哈哈哈

**Comment by wwwsure** [comment]
好了好了，现在好了

**Comment by Xhofe** [comment]
已经存在LocalStorage
