### ISSUE TITLE
如何把在alistdesktop通过webdav挂载到其他局域网设备上而不是仅仅是在本地计算机上

### ISSUE THREAD

**Issue by bjh021149** [alist-org/desktop-release#45]
psgui界面挂载设置里的网络模式是什么意思

**Comment by xhofe** [comment]
可以直接通过安装的设备上的ip挂载 按照此填写 https://alist.nn.ci/zh/guide/webdav.html

gui界面中的网络模式是指Windows中的一种网络磁盘格式。
