### ISSUE TITLE
[BUG] Mac 挂载到本地后可以看到不断扫描文件导致风控

### ISSUE THREAD

**Issue by killsting** [alist-org/desktop-release#49]
### 使用的存储

所有存储方式

### 问题描述

挂载在 Mac Finder 的存储盘，会看到频繁读取扫描文件会导致网盘被风控，用 CloudMounter 的时候没有发生过这个问题。请问这个是正常的吗？

### 复现步骤

无

### 相关日志

无

#### AList日志

无

#### 挂载日志

无

**Comment by xhofe** [comment]
应用不会主动扫盘，应该是其他软件的行为。
