### ISSUE TITLE
Macos本地挂载后，如何手动刷新本地目录？以及自动刷新的逻辑是什么（挂载的缓存模式，选择的关闭）

### ISSUE THREAD

**Issue by arthurxxy** [alist-org/desktop-release#50]
### 复现步骤

1. 添加……
2. ……
3. ……

#### AList日志

```log
……
```

#### 挂载日志

```log
……
```

**Comment by xhofe** [comment]
这里存在两处缓存：
- alist服务端的缓存，在添加存储时设置
- 挂载处的缓存：默认五分钟，可以在自定义参数中设置

```
--dir-cache-time 5m0s
```

即表示默认的5分钟0秒

**Comment by arthurxxy** [comment]
感谢解答

Andy Hsu ***@***.***> 于2024年3月4日周一 16:54写道：
