### ISSUE TITLE
阿里云盘的挂载

### ISSUE THREAD

**Issue by bjh021149** [alist-org/desktop-release#53]
阿里云盘只能挂载资源盘不能不能挂载备份盘是软件的问题，还是阿里云的问题・_・?看文档是被封了，额，但是封应该是全封吧。我就是在确认下。

**Comment by xhofe** [comment]
测试了一下 都可以挂载
不能挂载提示什么？
注意切换备份和资源需要进入文件夹点一下右下角的刷新生效
