### ISSUE TITLE
[BUG] linux版本启动报错

### ISSUE THREAD

**Issue by zhxknb1** [alist-org/desktop-release#55]
### 复现步骤

1. 运行环境见截图
2. ……
3. ……
![E3E249986F3D2FB334C2CCDD370B397D](https://github.com/alist-org/desktop-release/assets/59738277/75e72807-afc3-4d4e-a87d-9485bd2a365c)

#### AList日志

```log
……
```

#### 挂载日志

```log
……
```

**Comment by zhxknb1** [comment]
ubuntu 22.04

**Comment by xhofe** [comment]
需要桌面版安装启动，非命令行。
