### ISSUE TITLE
已激活的设备变成未激活状态

### ISSUE THREAD

**Issue by DANTHK** [alist-org/desktop-release#67]
### 使用的存储驱动

夸克/阿里云open

### 问题描述

Mac Arm desktop版本，我现在在M2芯片用，但是Alist总是会变成非激活状态，需要重新反激活然后再激活。它把我的一个设备识别成了多个设备。
<img width="751" alt="image" src="https://github.com/user-attachments/assets/1cdec0a0-6ff8-4f7e-8efe-8de1870ae009">
如上图，圈中的是这三个主机名是一台设备，我也没有升级过系统，也没有改过主机名。

### 复现步骤

好像是更新版本？不确定

#### AList日志

```log
……
```

#### 挂载日志

```log
……
```

**Comment by xhofe** [comment]
这是因为Mac切换网络时会导致hostname也改变了 所以需要固定一下hostname

**Comment by xhofe** [comment]
https://itlanyan.com/macos-set-pemanent-hostname/
