### ISSUE TITLE
软件启动失败，一直转圈

### ISSUE THREAD

**Issue by wwwsure** [alist-org/desktop-release#7]
![I5$H7S IJDH9}R$1D8@DCZ5](https://user-images.githubusercontent.com/80196042/229445959-c0b385d3-47d7-484b-b7f6-492ddaf446a6.png)
大佬看一看这个，一天了已经

**Comment by chenspnjupt** [comment]
碰到同样的问题，看下是不是windows安全中心，扫描到了威胁，将目录：C:\Program Files\alist-desktop加入到扫描排除项中

**Comment by wwwsure** [comment]
> 碰到同样的问题，看下是不是windows安全中心，扫描到了威胁，将目录：C:\Program Files\alist-desktop加入到扫描排除项中

你的解决了吗兄弟

**Comment by wwwsure** [comment]
为啥会这样呀大佬

**Comment by Xhofe** [comment]
已经在v3.15.1使用非upx版本以避免windows误删，如果仍被误删将安装目录（默认为C:\Program Files\alist-desktop）加入到扫描排除项中或者检查其他安全类软件的删除操作。
