### ISSUE TITLE
大佬，为什么会挂在后台莫名奇妙就会停止

### ISSUE THREAD

**Issue by wwwsure** [alist-org/desktop-release#9]
大佬，为什么会挂在后台莫名奇妙就会停止，在启动的话就会一直转圈。重新安装才能解决，但是过不了一天吧，又会停止，是我的key有什么问题吗
![NHNL7$FNM7I}YC J%`D C8A](https://user-images.githubusercontent.com/80196042/230333136-e37560f6-dfc6-4e2e-b3e0-165c93303ce4.png)
![YR~@BYGCYE%5%YW$S1({2NU](https://user-images.githubusercontent.com/80196042/230333145-7d3e2873-42e0-4ac9-95b0-16cbfdc61ee8.png)
![_NYRDB)TEE59FBV0TU 7T@R](https://user-images.githubusercontent.com/80196042/230333211-f60ba199-5164-45af-8c18-905da3808188.png)

**Comment by Xhofe** [comment]
已经在v3.15.1使用非upx版本以避免windows误删，如果仍被误删将安装目录（默认为C:\Program Files\alist-desktop）加入到扫描排除项中或者检查其他安全类软件的删除操作。
